import React, { useState } from 'react';
import AIPrompt from './AIPrompt';
import EnglishToAmharicTranslator from './EnglishToAmharicTranslator';
import AmharicKeyboard from './AmharicTransliteration';
import SimpleTranslator from './SimpleTranslator';


const Translators = () => {
  const [generatedText, setGeneratedText] = useState('');
  const [translatedText, setTranslatedText] = useState('');

  const handleTranslatedTextChange = (text) => {
    setTranslatedText(text);
  };

  const handleGeneratedText = (text) => {
    setGeneratedText(text);
  };

  return (
    <div>
      <AmharicKeyboard onTranslatedTextChange={handleTranslatedTextChange} />
      <AIPrompt onGeneratedText={handleGeneratedText} englishText={translatedText} />
      <EnglishToAmharicTranslator englishTextTranslate={generatedText} />
      <SimpleTranslator />
      <p style={{ marginLeft:'10px', marginRight: '10px' }}>አመልካች ፦ ኤ አይ ለጥያቄዎቹ የሚሰጠው መልስ ሁልጊዜ ሙሉ በሙሉ ትክክል ላይሆን ወይም በቅርብ ጊዜ የተከናወኑትን ነገሮች ሊያንጸባርቅ ይችላል ።</p>
      <p style={{ marginLeft:'10px', marginRight: '10px' }}>Disclaimer: The answers generated by the AI may not always be completely accurate or reflect the latest developments.</p>
    </div>
  );
   
};


export default Translators;






